spring:
  sql:
    init:
      mode: always
  application:
    name: cms
  threads:
    virtual:
      enabled: true
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password: password
  datasource:
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
  docker:
    compose:
      lifecycle-management: start_only
  profiles:
    default: "local"
  config:
    activate:
      on-profile: "local"

server:
  tomcat:
    threads:
      max: 250